---

flask:
  debug: false
  threaded: true
  host: 0.0.0.0
  port: 8000

redis:
  host: 127.0.0.1
  port: 6379
  db: 0
  password: null

oauth:
  client_id: foo-bar-baz-token
  client_secret: secret
