---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: https-only
  namespace: getlock
spec:
  redirectScheme:
    scheme: https
    permanent: true

---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: stripprefix-api-v1
  namespace: getlock
spec:
  stripPrefix:
    prefixes:
      - /api/v1

---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: stripprefix-docs
  namespace: getlock
spec:
  stripPrefix:
    prefixes:
      - /docs
