---

apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: getlock
data:
  config: |
    ---

    flask:
      debug: false
      threaded: true
      host: 0.0.0.0
      port: 8000

    redis:
      host: redis.getlock.svc.cluster.local
      port: 6379
      db: 1
      password: null
